SELECT
--EC_CATEG_ITEM.ITEM_NO,
EC_CATEG.PARENT_ID,
EC_CATEG.CATEG_ID,
--EC_CATEG_ITEM.CATEG_ID,
EC_CATEG.DESCR


FROM EC_CATEG

--JOIN EC_CATEG_ITEM
--ON EC_CATEG_ITEM.CATEG_ID = EC_CATEG.CATEG_ID

-- I need to convert EC_CATEG.PARENT_ID to the DESCR Value of it.
