SELECT
'SKU' AS 'Item Type',
NULL AS 'Product ID',
IM_ITEM.ADDL_DESCR_1 AS "Product Name"

FROM IM_INV_CELL

JOIN IM_ITEM
ON IM_ITEM.ITEM_NO = IM_INV_CELL.ITEM_NO
JOIN IM_BARCOD
ON IM_BARCOD.DIM_1_UPR  = IM_INV_CELL.DIM_1_UPR

WHERE

IM_BARCOD.BARCOD_ID = 'ITEM' AND
IM_INV_CELL.LOC_ID = 'MAIN' AND
IM_INV_CELL.QTY_ON_HND > '0'
