SELECT TOP 100
IM_BARCOD.ITEM_NO AS 'CounterPoint Item Number',
IM_BARCOD.BARCOD AS "Product Code/SKU",
IM_BARCOD.DIM_1_UPR,
IM_BARCOD.DIM_2_UPR,
IM_BARCOD.DIM_3_UPR,
IM_INV.QTY_AVAIL AS 'QTY',
IM_INV_CELL.QTY_AVAIL AS 'CELL QTY'

FROM IM_BARCOD
JOIN IM_ITEM
ON IM_BARCOD.ITEM_NO = IM_ITEM.ITEM_NO
JOIN IM_INV
ON IM_BARCOD.ITEM_NO = IM_INV.ITEM_NO

JOIN IM_INV_CELL
ON IM_BARCOD.ITEM_NO = IM_INV_CELL.ITEM_NO
--ON IM_BARCOD.DIM_1_UPR = IM_INV_CELL.DIM_1_UPR AND
--IM_BARCOD.DIM_2_UPR = IM_INV_CELL.DIM_2_UPR AND
--IM_BARCOD.DIM_3_UPR = IM_INV_CELL.DIM_3_UPR
WHERE
BARCOD_ID = 'ITEM' AND
IM_INV.QTY_AVAIL > 0 AND
IM_ITEM.TRK_METH = 'G'
