SELECT TOP 25
EC_CATEG_ITEM.ITEM_NO,
EC_CATEG_ITEM.CATEG_ID,
EC_CATEG.DESCR,
EC_CATEG.PARENT_ID

FROM EC_CATEG_ITEM

JOIN EC_CATEG
ON EC_CATEG_ITEM.CATEG_ID = EC_CATEG.CATEG_ID

JOIN IM_ITEM
ON EC_CATEG_ITEM.ITEM_NO = IM_ITEM.ITEM_NO
