SELECT
IM_ITEM.TRK_METH,
IM_INV_CELL.ITEM_NO,
IM_BARCOD.BARCOD,
IM_INV_CELL.DIM_1_UPR,
IM_INV_CELL.DIM_2_UPR,
IM_INV_CELL.DIM_3_UPR,
IM_INV_CELL.QTY_ON_HND

FROM IM_ITEM

JOIN IM_INV_CELL
ON IM_ITEM.ITEM_NO = IM_INV_CELL.ITEM_NO

JOIN IM_BARCOD
ON IM_INV_CELL.DIM_1_UPR = IM_BARCOD.DIM_1_UPR AND
IM_INV_CELL.DIM_2_UPR = IM_BARCOD.DIM_2_UPR AND
IM_INV_CELL.DIM_3_UPR = IM_BARCOD.DIM_3_UPR 

WHERE
IM_INV_CELL.QTY_ON_HND > 0 AND
IM_BARCOD.BARCOD_ID = 'ITEM'
